export { default as Carved_big } from './carved_big.png';
export { default as Carved_rectangle } from './carved_rectangle.png';
export { default as Carved_square } from './carved_square.png';
export { default as Connection_down } from './connection_down.png';
export { default as Connection_left } from './connection_left.png';
export { default as Connection_right } from './connection_right.png';
export { default as Connection_up } from './connection_up.png';
export { default as Horizontal } from './horizontal.png';
export { default as Vertical } from './vertical.png';